Repository facebook/jemalloc, pull requests merged in 2025-08, with the labels that each got.

#23 Do not dehugify when purging
  include/jemalloc/internal/hpa_hooks.h
  src/hpa.c
  src/hpa_hooks.c
  test/unit/hpa.c
  test/unit/hpa_vectorized_madvise.c
  test/unit/hpa_vectorized_madvise_large_batch.c
Labels: cla signed

#22 Use relaxed atomics to access the process madvise pid fd
  src/pages.c
Labels: cla signed

#17 Experimental configuration option for fast path prefetch from cache_bin
  configure.ac
  include/jemalloc/internal/jemalloc_internal_defs.h.in
  include/jemalloc/internal/jemalloc_internal_inlines_c.h
Labels: cla signed

#31 Remove an unused function and global variable
  test/unit/hpa_vectorized_madvise_large_batch.c
Labels: cla signed

#32 Fix the compilation check for process madvise
  configure.ac
Labels: cla signed

#36 Remove pidfd_open call handling and rely on PIDFD_SELF
  configure.ac
  include/jemalloc/internal/pages.h
  src/jemalloc.c
  src/pages.c
Labels: enhancement, cla signed, cleanup

#37 Always use pthread_equal to compare thread IDs
  src/jemalloc.c
  src/tsd.c
Labels: cla signed, bug-fix
